<?php

/**
 * @file
 * Provides an income source entity type.
 */

use Drupal\Core\Render\Element;
use Drupal\personal_budget_tracker\Entity\IncomeSource;
use Drupal\user\UserInterface;

/**
 * Implements hook_theme().
 */
function personal_budget_tracker_theme() {
  return [
    'income_source' => [
      'render element' => 'elements',
    ],
  ];
}

/**
 * Prepares variables for income source templates.
 *
 * Default template: income-source.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - elements: An associative array containing the income source information and any
 *     fields attached to the entity.
 *   - attributes: HTML attributes for the containing element.
 */
function template_preprocess_income_source(array &$variables) {
  $variables['view_mode'] = $variables['elements']['#view_mode'];
  foreach (Element::children($variables['elements']) as $key) {
    $variables['content'][$key] = $variables['elements'][$key];
  }
}

/**
 * Implements hook_user_cancel().
 */
function personal_budget_tracker_user_cancel($edit, UserInterface $account, $method) {
  switch ($method) {
    case 'user_cancel_reassign':
      // Anonymize income sources.
      $storage = \Drupal::entityTypeManager()->getStorage('income_source');
      $income_source_ids = $storage->getQuery()
        ->condition('uid', $account->id())
        ->execute();
      foreach ($storage->loadMultiple($income_source_ids) as $income_source) {
        $income_source->setOwnerId(0);
        $income_source->save();
      }
      break;
  }
}

/**
 * Implements hook_ENTITY_TYPE_predelete() for user entities.
 */
function personal_budget_tracker_user_predelete(UserInterface $account) {
  // Delete income sources.
  $storage = \Drupal::entityTypeManager()->getStorage('income_source');
  $income_source_ids = $storage->getQuery()
    ->condition('uid', $account->id())
    ->execute();
  $income_sources = $storage->loadMultiple($income_source_ids);
  $storage->delete($income_sources);
}
